config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "home#index"

  resources :containers do
    member do
      patch :mark_as_shipped
      patch :mark_as_not_shipped
      get :pick
      post :add_item
      delete :remove_item
      get :items
      get :summary
      get :manifest
      get :certificate_of_donation
      get :packing_list
    end
    collection do
      get :choose_for_picking
    end
  end
  resources :inventory_items do
    collection do
      get :barcode_lookup
      post :barcode_lookup, to: "inventory_items#do_barcode_lookup"
      get :by_category
    end
  end
  resources :item_subcategories, except: :index do
    collection do
      get "picker"
    end
  end
  resources :item_categories do
    collection do
      get :hierarchy
  end
  end
  resources :settings, only: [ :index, :edit, :update ]
  resources :users, except: :destroy, constraints: { id: /[0-9]+/ } do
    collection do
      post "login"
      delete "logout"
    end
  end
end

app/models/inventory_item.rb
require "csv"

class InventoryItem < ApplicationRecord
  belongs_to :item_subcategory
  belongs_to :inventoried_by, class_name: "User", inverse_of: :packed_items
  belongs_to :container, optional: true
  belongs_to :picked_by, class_name: "User", inverse_of: :packed_items, optional: true

  enum :manual_type, [ :no_manual, :pdf, :paper ]
  enum :status, [ :in_inventory, :in_container, :discarded_stale_dated, :discarded_damaged, :lost, :given_away ]

  delegate :equipment?, :supply?, :item_category, :item_category_id, :classification, to: :item_subcategory, allow_nil: true

  validates :barcode, presence: true, uniqueness: true, format: { with: /[0-9]{1,8}/ }
  validates :oldest_expiry_year, numericality: { in: 1900..2100 }, allow_blank: true
  validates :manual_type, presence: true, if: :equipment?
  validates :status, inclusion: { in: [ "in_container" ] }, if: :container
  validates :status, exclusion: { in: [ "in_container" ] }, unless: :container
  validates :status, presence: true
  validates :container_id, absence: true, unless: :in_container?
  validates :container_id, presence: true, if: :in_container?

  STATUS_DISPLAYS = {
    in_inventory: "Inventory",
    in_container: "Container",
    discarded_stale_dated: "Stale dated",
    discarded_damaged: "Damaged",
    lost: "Lost",
    given_away: "Given away"
  }

  MANUAL_TYPE_DISPLAYS = {
    no_manual: "None",
    pdf: "PDF",
    paper: "Paper"
  }

  def status_display
    STATUS_DISPLAYS[status.to_sym]
  end

  def manual_type_display
    MANUAL_TYPE_DISPLAYS[manual_type.to_sym]
  end

  def editable?
    container.nil?
  end

  def destroyable?
    container.nil?
  end

  def can_be_added_to_container_failure_reason
    return "Item is already in container #{container.application_number}" if container
    return "Item has status #{status}" unless in_inventory?
    nil
  end

  def can_be_added_to_container?
    can_be_added_to_container_failure_reason.nil?
  end

  def add_to_container!(container_to_add_to, picked_by:)
    raise "Container cannot receive items" unless container_to_add_to.can_receive_items?
    raise "Item already in a container" unless can_be_added_to_container?
    update!(container: container_to_add_to, status: :in_container, picked_at: DateTime.now, picked_by:)
  end

  def remove_from_container!
    raise "Item not in a container" unless container
    raise "Items cannot be removed from container" unless container.can_receive_items?
    update!(container: nil, status: :in_inventory, picked_at: nil, picked_by_id: nil)
  end

  def expiry_date_options
    default_options = (Date.current.year - 2)..(Date.current.year + 2)
    return default_options if oldest_expiry_year.nil? || default_options.include?(oldest_expiry_year)

    oldest_expiry_year..(Date.current.year + 2)
  end

  def weight
    item_subcategory.weight_kg || item_category.weight_kg || 0
  end

  def value
    item_subcategory.value || item_category.value || 0
  end

  def self.to_csv
    CSV.generate(headers: true) do |csv|
      csv << [ "Barcode", "Packed at", "Packed by", "Classification", "Category", "Subcategory", "Description", "Manual type", "Oldest expiry year", "Status", "Container", "Picked at", "Picked by" ]

      find_each do |item|
        csv << item.csv_values
      end
    end
  end

  def csv_values
    [ barcode, created_at, inventoried_by&.initials, classification, item_category&.name, item_subcategory&.name, description, manual_type_display, oldest_expiry_year, status_display, container&.application_number, picked_by&.initials, picked_at ]
  end
end

app/controllers/inventory_items_controller.rb
class InventoryItemsController < ApplicationController
  before_action :set_inventory_item, only: [ :show, :edit, :update, :destroy ]
  before_action :authorize_packer!, only: [ :new, :create, :edit, :update, :destroy ]
  before_action :authorize_admin!, only: [ :index, :barcode_lookup, :by_category ]

  def new
    @breadcrumbs = [ index_breadcrumb, "New" ]
    @body_class = "inventory-entry"
    @inventory_item = InventoryItem.new(barcode: params[:barcode])

    preselected_subcategory = current_user.recently_packed_item&.item_subcategory
    if preselected_subcategory
      @classification = preselected_subcategory.classification
      @item_category_id = preselected_subcategory.item_category_id
      @item_subcategory_id = preselected_subcategory.id
    end
  end

  def create
    @inventory_item = InventoryItem.new(inventory_item_params)
    @inventory_item.inventoried_by = current_user
    @inventory_item.item_subcategory_id = params[:item_subcategory_id]
    if @inventory_item.save
      flash[:highlight_inventory_item_id] = @inventory_item.id
      redirect_to new_inventory_item_path
    else
      @breadcrumbs = [ index_breadcrumb, "New" ]
      @body_class = "inventory-entry"
      render :new, status: :unprocessable_entity
    end
  end

  def index
    items = view_context.apply_inventory_item_sorts_and_filters(InventoryItem)
    respond_to do |format|
      format.html do
        @inventory_items = apply_pagy(items)
        @breadcrumbs = [ "Inventory" ]
      end
      format.csv do
        send_data items.to_csv, filename: "inventory-items-#{Time.current.strftime('%Y%m%d-%H%M%S')}.csv"
      end
    end
  end

  def by_category
    scope = InventoryItem
    scope = scope.where(status: params[:status]) if params[:status].present?
    @inventory_items_by_subcategory = scope.group(:item_subcategory_id).count
    @subcategories = ItemSubcategory.joins(:item_category).where(id: @inventory_items_by_subcategory.keys).order(item_categories: { name: :asc }, item_subcategories: { catchall: :asc, name: :asc })
    @breadcrumbs = [ index_breadcrumb, "By category" ]
  end

  def show
    @breadcrumbs = [ index_breadcrumb, @inventory_item.barcode ]
  end

  def edit
    @breadcrumbs = [ index_breadcrumb, [ @inventory_item.barcode, inventory_item_path(@inventory_item) ], "Edit" ]
    @body_class = "inventory-entry"
    render :new
  end

  def update
    if @inventory_item.update(inventory_item_params)
      redirect_to @inventory_item, notice: "Inventory item was successfully updated."
    else
      @breadcrumbs = [ index_breadcrumb, [ @inventory_item.barcode, inventory_item_path(@inventory_item) ], "Edit" ]
      @body_class = "inventory-entry"
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @inventory_item.destroy
    if params[:context] == "inventory_entry"
      redirect_to new_inventory_item_path
    else
      redirect_to inventory_items_url, notice: "Inventory item was successfully destroyed."
    end
  end

  def barcode_lookup
    @breadcrumbs = [ index_breadcrumb, "Barcode lookup" ]
  end

  def do_barcode_lookup
    inventory_item = InventoryItem.find_by(barcode: params[:barcode])
    if inventory_item
      redirect_to inventory_item
      return
    end

    @message = "No item with barcode #{params[:barcode]} found. #{view_context.link_to('Add it?', new_inventory_item_path(barcode: params[:barcode]))}"
    @breadcrumbs = [ index_breadcrumb, "Barcode lookup" ]
    render :barcode_lookup, status: :not_found
  end

  private

  def set_inventory_item
    @inventory_item = InventoryItem.find(params[:id])
  end

  def inventory_item_params
    params.require(:inventory_item).permit(:barcode, :oldest_expiry_year, :description, :manual_type, :status)
  end

  def index_breadcrumb
    current_user&.admin? ? [ "Inventory", inventory_items_path ] : "Inventory"
  end
end

app/helpers/inventory_item_helper.rb
module InventoryItemHelper
  def apply_inventory_item_sorts_and_filters(inventory_items, context: nil)
    inventory_items = inventory_items.includes(item_subcategory: :item_category, picked_by: {}, inventoried_by: {}, container: {})

    if params[:inventory_item_filter]
      params[:inventory_item_filter].select { |_k, v| v.present? }.each do |key, value|
        inventory_items = case key
        when "status"
                            inventory_items.where(status: value)
        when "category"
                            if [ "equipment", "supply" ].include?(value)
                              inventory_items.joins(item_subcategory: :item_category).where(item_category: { classification: ItemCategory.classifications[value.to_sym] })
                            else
                              inventory_items.joins(:item_subcategory).where(item_subcategory: { item_category_id: value })
                            end
        when "oldest_expiry_year"
                            inventory_items.where(oldest_expiry_year: value)
        when "container"
                            inventory_items.where(container_id: value)
        else
                            raise "Unexpected filter key #{key}"
        end
      end
    end

    case params[:inventory_item_sort]
    when "barcode"
      inventory_items.order(:barcode)
    when "category"
      inventory_items.order("item_category.name", "item_subcategory.name", created_at: :desc)
    when "status"
      inventory_items.order(:status, created_at: :desc)
    when "packed_by"
      inventory_items.left_joins(:inventoried_by).order(inventoried_by: { initials: :asc }, created_at: :desc)
    when "picked_at"
      inventory_items.order(Arel.sql("picked_at DESC NULLS LAST"), created_at: :desc)
    when "picked_by"
      inventory_items.left_joins(:picked_by).order(Arel.sql("picked_by.initials NULLS LAST"), created_at: :desc)
    when "oldest_expiry_year"
      inventory_items.order(Arel.sql("oldest_expiry_year DESC NULLS LAST"), created_at: :desc)
    when "container"
      inventory_items.order(Arel.sql("container_id DESC NULLS LAST"), created_at: :desc)
    when nil
      if context == :picking
        inventory_items.order(Arel.sql("picked_at DESC NULLS LAST"), created_at: :desc)
      else
        inventory_items.order(created_at: :desc)
      end
    else
      raise "Unexpected sort #{params[:inventory_item_sort]}"
    end
  end

  def grouped_item_category_options
    [ :equipment, :supply ].map do |classification|
      [ classification.to_s.humanize, ItemCategory.where(classification:).order(:name).map { |category| [ category.name, category.id ] } ]
    end
  end

  def category_select_options
    [
      [ "Equipment",
        [ [ "(All equipment)", "equipment" ] ] + ItemCategory.where(classification: :equipment).order(:name).map { |c| [ c.name, c.id ] }
      ],
      [ "Supplies",
        [ [ "(All supplies)", "supply" ] ] + ItemCategory.where(classification: :supply).order(:name).map { |c| [ c.name, c.id ] }
      ]
    ]
  end
end

app/views/inventory_items/_barcode_field.html.erb
<%# locals: (form:) -%>
<div class="form-group">
  <%= form.text_field :barcode, class: "barcode form-control", required: true, autofocus: true, autocomplete: :off, inputmode: :numeric, pattern: '[0-9]{1,8}' %>
  <div class="barcode-ready">Ready to scan</div>
  <div class="barcode-not-ready"><%= form.label :barcode, 'Click here before scanning' %></div>
  <div class="barcode-entered-not-ready"><%= form.label :barcode, 'Click here to rescan' %></div>
</div>

app/views/inventory_items/barcode_lookup.html.erb
<div id="barcode-lookup">
  <%= form_with(url: barcode_lookup_inventory_items_path, method: :POST, local: true) do |form| %>
    <%= render partial: 'barcode_field', locals: { form: } %>
  <% end %>
  <% if @message.present? %>
    <p id="barcode-lookup-result"><%= @message.html_safe %></p>
  <% end %>
</div>

app/views/inventory_items/by_category.html.erb
<div class="report-filters">
  View results with status:
  <%= form_with method: :get, class: 'inline-form' do %>
    <%= select_tag 'status',
        options_for_select([['(All items)', '']] + InventoryItem::STATUS_DISPLAYS.map { |status, label| [label, status] }, params[:status]),
        onchange: 'this.form.submit();' %>
  <% end %>
</div>

<% inventory_link_params = params[:status].present? ? { 'inventory_item_filter[status]' => params[:status] } : {} %>

<table class="report-table">
  <tbody>
    <% current_category = nil %>
    <% current_category_count = 0 %>
    <% @subcategories.each do |subcategory| %>
      <% if current_category != subcategory.item_category %>
        <% if current_category %>
          <tr class="total-row">
            <td colspan="2"></td>
            <td class="numeric"><%= link_to(current_category_count, inventory_items_path(**inventory_link_params, 'inventory_item_filter[category]' => current_category.id)) %></td>
          </tr>
          <% current_category_count = 0 %>
        <% end %>
        <% current_category = subcategory.item_category %>
        <tr>
          <td colspan="2"><b><%= link_to(current_category.name, current_category) %></b></td>
        </tr>
      <% end %>
      <tr>
        <td></td>
        <td><%= link_to(subcategory.name, subcategory) %></td>
        <td class="numeric"><%= @inventory_items_by_subcategory[subcategory.id] %></td>
      </tr>
      <% current_category_count += @inventory_items_by_subcategory[subcategory.id] %>
    <% end %>
    <% if current_category %>
      <tr class="total-row">
        <td colspan="2"></td>
        <td class="numeric"><%= link_to(current_category_count, inventory_items_path(**inventory_link_params, 'inventory_item_filter[category]' => current_category.id)) %></td>
      </tr>
    <% end %>
    <tr class="total-row">
      <td colspan="2">Total items</td>
      <td class="numeric"><%= @inventory_items_by_subcategory.values.sum %></td>
    </tr>
  </tbody>
</table>

app/views/inventory_items/index.html.erb
<div class="page-actions">
  <p>
    <%= link_to('New', new_inventory_item_path, class: "btn") %>
    <%= link_to 'Barcode lookup', barcode_lookup_inventory_items_path, class: "btn" %>
    <%= link_to 'By category count', by_category_inventory_items_path, class: "btn" %>
  <p>
</div>

<%= turbo_frame_tag 'inventory_items_list', target: '_top' do %>
  <table class="data-table">
    <% if params[:inventory_item_filter]&.to_unsafe_h&.any?{|k, v| v.present?} %>
      <caption>
        Filters applied. <%= link_to 'Clear.', request.path %>
      </caption>
    <% end %>
    </caption>
    <thead>
      <tr>
        <th>Created <%= list_sort_link(param_name: :inventory_item_sort, param_value: nil) %></th>
        <th class="numeric">Barcode <%= list_sort_link(param_name: :inventory_item_sort, param_value: :barcode) %></th>
        <th>
          Category <%= list_sort_link(param_name: :inventory_item_sort, param_value: :category) %>
          <%= list_filter_control(scope: :inventory_item_filter, column: :category, control_type: :grouped_select, options: category_select_options) %>
        </th>
        <th>Packed by <%= list_sort_link(param_name: :inventory_item_sort, param_value: :packed_by) %></th>
        <th>
          Status 
          <%= list_sort_link(param_name: :inventory_item_sort, param_value: :status) %>
          <%= list_filter_control(scope: :inventory_item_filter, column: :status, control_type: :select, options: [['']] + InventoryItem.statuses.keys.map { |c| [InventoryItem::STATUS_DISPLAYS[c.to_sym], c] }) %>
        </th>
        <th>
          Container
          <%= list_sort_link(param_name: :inventory_item_sort, param_value: :container) %>
          <%= list_filter_control(scope: :inventory_item_filter, column: :container, control_type: :select, options: [['']] + Container.order(application_number: :desc).map { |c| [c.display_text, c.id] }) %>
        </th>
        <th>
          Expiry
          <%= list_sort_link(param_name: :inventory_item_sort, param_value: :oldest_expiry_year) %>
          <%= list_filter_control(scope: :inventory_item_filter, column: :oldest_expiry_year, control_type: :year) %>
          </th>
        <th>Picked at <%= list_sort_link(param_name: :inventory_item_sort, param_value: :picked_at) %></th>
        <th>Picked by <%= list_sort_link(param_name: :inventory_item_sort, param_value: :picked_by) %></th>
      </tr>
    </thead>
    <tbody>
      <% @inventory_items.each do |inventory_item| %>
        <tr>
          <td><%= render_datetime(inventory_item.created_at) %></td>
          <td class="numeric"><%= inventory_item.barcode %></td>
          <td><%= link_to(inventory_item.item_subcategory.display_name, inventory_item.item_subcategory) %></td>
          <td><%= render_user(inventory_item.inventoried_by) %></td>
          <td><%= inventory_item.status_display %></td>
          <td>
            <%= link_to(inventory_item.container.short_display_text, inventory_item.container, title: inventory_item.container.display_text) if inventory_item.container %>
          </td>
          <td><%= inventory_item.oldest_expiry_year %>
          <td><%= render_datetime(inventory_item.picked_at) %></td>
          <td><%= render_user(inventory_item.picked_by) %></td>
          <td class="action-column"><%= link_to '🔎', inventory_item_path(inventory_item), title: 'View' %></td>
          <td class="action-column">
            <% if current_user.packer_access? %>
              <%= link_to('✎', edit_inventory_item_path(inventory_item), title: 'Edit') if inventory_item.editable? %>
            <% end %>
          </td>
          <td class="action-column">
            <% if current_user.packer_access? %>
              <%= link_to("🗑", inventory_item, title: 'Delete', data: { turbo_method: :delete, turbo_confirm: "Deleting should only be done if this item never existed. Consider instead changing this item's status. Are you sure you want to delete?" }) if inventory_item.destroyable? %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%== render_pagy %>
  <p>
    <%= link_to 'Download CSV', inventory_items_path(format: :csv, params: request.query_parameters), class: "btn" %>
  </p>
<% end %>

app/views/inventory_items/new.html.erb
<div id="inventory-entry-area">
  <%= form_with(model: @inventory_item, local: true) do |form| %>
    <div class="form-group">
      <label>Barcode</label>
      <%= render partial: 'barcode_field', locals: { form: } %>
    </div>

    <div class="form-group">
      <label>Category</label>
      <%= turbo_frame_tag 'item_subcategory_picker', src: picker_item_subcategories_path(classification: @inventory_item.classification || @classification, item_category_id: @inventory_item.item_category_id || @item_category_id, item_subcategory_id: @inventory_item.item_subcategory_id || @item_subcategory_id) %>
    </div>

    <div class="form-group">
      <%= form.label :oldest_expiry_year %>
      <%= form.radio_button :oldest_expiry_year, '', required: true %>
      <%= form.label :oldest_expiry_year_, 'None', class: 'radio-label' %>
      <% @inventory_item.expiry_date_options.each do |year| %>
        <%= form.label("oldest_expiry_year_#{year}", class: 'radio-label') do %>
          <%= form.radio_button :oldest_expiry_year, year, required: true %>
          <%= year %>
        <% end %>
      <% end %>
    </div>
    <div class="form-group manual-type">
      <%= form.label :manual_type, "Manual" %>
      <% InventoryItem.manual_types.keys.map{|m| [InventoryItem::MANUAL_TYPE_DISPLAYS[m.to_sym], m]}.each do |label, value| %>
        <%= form.label("manual_type_#{value}", class: 'radio-label') do %>
          <%= form.radio_button :manual_type, value, required: true %>
          <%= label %>
        <% end %>
      <% end %>
    </div>
    <div class="form-group">
      <%= form.label :description, "Description" %>
      <%= form.text_area :description, class: "form-control" %>
    </div>

    <% if !@inventory_item.in_container? && !@inventory_item.new_record? %>
      <div class="form-group">
        <%= form.label :status, "Status" %>
        <%= form.select :status, InventoryItem.statuses.keys.without('in_container').map { |c| [InventoryItem::STATUS_DISPLAYS[c.to_sym], c] }, {}, class: "form-control" %>
      </div>
    <% end %>

    <%= render partial: 'shared/validation_error', locals: { record: @inventory_item } %>

    <% if @inventory_item.new_record? %>
      <div class="form-actions">
        <%= form.submit "Add item to inventory" %>
        <%= link_to 'Cancel', '/' %>
      </div>
    <% else %>
      <div class="form-actions">
        <%= form.submit "Update inventory item" %>
        <%= link_to 'Cancel', inventory_item_path(@inventory_item) %>
      </div>
    <% end %>
  <% end %>
</div>

<div id="inventory-review-area">
  <%= turbo_frame_tag 'user_inventory_items_list', target: '_top' do %>
    <% inventory_items = apply_inventory_item_sorts_and_filters(current_user.most_recently_packed_items) %>

    <h2>Your recently created items</h2>
    <% if inventory_items.any? %>
      <table class="data-table">
        <thead>
          <tr>
            <th>Created</th>
            <th class="numeric">Barcode</th>
            <th>Category</th>
            <th>Status</th>
          </tr>
        </thead>
        <tbody>
          <% inventory_items.each do |inventory_item| %>
            <tr class="<%= 'highlight highlight-active' if inventory_item.id == flash[:highlight_inventory_item_id].to_i %>">
              <td><%= render_datetime(inventory_item.created_at) %>
              <td class="numeric"><%= inventory_item.barcode %> </td>
              <td><%= link_to(inventory_item.item_subcategory.display_name, inventory_item.item_subcategory) %></td>
              <td>
                <%= inventory_item.status_display %><% if inventory_item.container %>: <%= link_to(inventory_item.container.application_number, inventory_item.container) %><% end %>
              </td>
              <td class="action-column">
                <%= link_to '🔎', inventory_item_path(inventory_item), title: 'View' %>
              </td>
              <td class="action-column">
                <%= link_to '✎', edit_inventory_item_path(inventory_item), title: 'Edit' if inventory_item.editable? %>
              </td>
              <td class="action-column">
                <%= link_to("🗑", inventory_item_path(inventory_item, context: 'inventory_entry'), title: 'Delete', data: { turbo_method: :delete, turbo_frame: '_self', turbo_confirm: "Deleting should only be done if this item never existed. Consider instead changing this item's status. Are you sure you want to delete?" }) if inventory_item.destroyable? %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
      <p>No inventory items packed.</p>
    <% end %>
  <% end %>
</div>

app/views/inventory_items/show.html.erb
<% if current_user.packer_access? %>
  <div id="page-actions">
    <p>
      <%= link_to('Edit', edit_inventory_item_path(@inventory_item), class: "btn") if @inventory_item.editable? %>
      <%= link_to("Delete", @inventory_item, class: "btn", data: { turbo_method: :delete, turbo_confirm: "Deleting should only be done if this item never existed. Consider instead changing this item's status. Are you sure you want to delete?" }) if @inventory_item.destroyable? %>
    </p>
  </div>
<% end %>

<table class="data-table">
  <tbody>
    <tr>
      <th>Created</th>
      <td><%= render_datetime(@inventory_item.created_at) %>
    <tr>
      <th>Category</th>
      <td><%= link_to(@inventory_item.item_subcategory.display_name, @inventory_item.item_subcategory) %></td>
    </tr>
    <tr>
      <th>Status</th>
      <td><%= @inventory_item.status_display %></td>
    <tr>
      <th>Container</th>
      <td><%= link_to(@inventory_item.container.display_text, @inventory_item.container) if @inventory_item.container %>
    </tr>
    <tr>
      <th>Packed by</th>
      <td><%= @inventory_item.inventoried_by.name %></td>
    </tr>
    <tr>
      <th>Manual</th>
      <td><%= @inventory_item.manual_type_display %></td>
    </tr>
    <tr>
      <th>Barcode</th>
      <td><%= @inventory_item.barcode %></td>
    </tr>
    <tr>
      <th>Oldest expiry year</th>
      <td><%= @inventory_item.oldest_expiry_year %></td>
    </tr>
  </tbody>
</table>