config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "home#index"

  resources :containers do
    member do
      patch :mark_as_shipped
      patch :mark_as_not_shipped
      get :pick
      post :add_item
      delete :remove_item
      get :items
      get :summary
      get :manifest
      get :certificate_of_donation
      get :packing_list
    end
    collection do
      get :choose_for_picking
    end
  end
  resources :inventory_items do
    collection do
      get :barcode_lookup
      post :barcode_lookup, to: "inventory_items#do_barcode_lookup"
      get :by_category
    end
  end
  resources :item_subcategories, except: :index do
    collection do
      get "picker"
    end
  end
  resources :item_categories do
    collection do
      get :hierarchy
  end
  end
  resources :settings, only: [ :index, :edit, :update ]
  resources :users, except: :destroy, constraints: { id: /[0-9]+/ } do
    collection do
      post "login"
      delete "logout"
    end
  end
end

app/models/container.rb
require "csv"

class Container < ApplicationRecord
  has_many :inventory_items, dependent: :nullify

  validates :application_number, presence: true

  scope :can_receive_items, -> { where(shipped_at: nil) }

  def mark_as_shipped!
    raise "Already shipped" unless can_be_marked_as_shipped?

    update!(shipped_at: Time.now)
  end

  def mark_as_not_shipped!
    raise "Already not shipped" unless shipped?

    update!(shipped_at: nil)
  end

  def can_be_marked_as_shipped?
    !shipped?
  end

  def editable?
    !shipped?
  end

  def destroyable?
    !shipped? && inventory_items.empty?
  end

  def display_text
    "##{application_number} - #{consignee_name} #{consignee_country}"
  end

  def short_display_text
    "##{application_number}"
  end

  def can_receive_items?
    !shipped?
  end

  def shipped?
    shipped_at.present?
  end

  def consignee_city_region_country
    [ consignee_city, consignee_region, consignee_country ].select(&:present?).join(", ")
  end

  def self.to_csv
    CSV.generate(headers: true) do |csv|
      csv << [ "Application number", "Created at", "Shipped at", "Consignee name", "Consignee address", "Consignee city", "Consignee region", "Consignee country", "Consignee postal code", "Consignee contact name", "Consignee contact email", "Consignee contact phone", "Item count" ]

      find_each do |container|
        csv << container.csv_values
      end
    end
  end

  def csv_values
    [ application_number, created_at, shipped_at, consignee_name, consignee_address, consignee_city, consignee_region, consignee_country, consignee_postal_code, consignee_contact_name, consignee_contact_email, consignee_contact_phone, inventory_items.count ]
  end
end

app/controllers/containers_controller.rb
class ContainersController < ApplicationController
  before_action :authorize_picker!, only: %i[choose_for_picking pick items summary add_item remove_item manifest certificate_of_donation packing_list]
  before_action :authorize_admin!, only: %i[new create edit update index show destroy mark_as_shipped mark_as_not_shipped]
  before_action :set_container, only: %i[show edit update destroy mark_as_shipped mark_as_not_shipped items summary manifest certificate_of_donation packing_list]

  layout "container_printable", only: %i[manifest certificate_of_donation packing_list]

  def new
    @breadcrumbs = [ [ "Containers", containers_path ], "New Container" ]
    next_application_number = Container.order(application_number: :desc).pick(:application_number).to_i + 1
    @container = Container.new(application_number: next_application_number)
  end

  def create
    @container = Container.new(container_params)
    if @container.save
      redirect_to container_path(@container)
    else
      render :new
    end
  end

  def index
    scope = Container.order(application_number: :desc)
    respond_to do |format|
      format.html do
        @containers = apply_pagy(scope)
        @breadcrumbs = [ "Containers" ]
      end
      format.csv do
        send_data scope.to_csv, filename: "containers-#{Time.current.strftime('%Y%m%d-%H%M%S')}.csv"
      end
    end
  end

  def show
    @breadcrumbs = [ [ "Containers", containers_path ], @container.display_text ]
  end

  def edit
    raise "Not editable" unless @container.editable?

    @breadcrumbs = [ [ "Containers", containers_path ], [ @container.display_text, container_path(@container) ], "Edit" ]
    render :new
  end

  def update
    raise "Not editable" unless @container.editable?

    respond_to do |format|
      if @container.update(container_params)
        format.html { redirect_to @container, notice: "Container was successfully updated." }
        format.json { render :show, status: :ok, location: @container }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @container.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    raise "Not destroyable" unless @container.destroyable?

    @container.destroy
    respond_to do |format|
      format.html { redirect_to containers_path, notice: "Container was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def mark_as_shipped
    @container.mark_as_shipped!

    respond_to do |format|
      format.html { redirect_to @container, notice: "Container marked as shipped." }
      format.json { render :show, status: :ok, location: @container }
    end
  end

  def mark_as_not_shipped
    @container.mark_as_not_shipped!

    respond_to do |format|
      format.html { redirect_to @container, notice: "Container marked as not shipped." }
      format.json { render :show, status: :ok, location: @container }
    end
  end

  def choose_for_picking
    @containers = Container.can_receive_items
    @breadcrumbs = [ "Picking" ]
  end

  def pick
    @container = Container.can_receive_items.find(params[:id])
    @breadcrumbs = [ [ "Picking", choose_for_picking_containers_path ], @container.display_text ]
    @success = flash[:success]
    @success_message = flash[:success_message]
    @body_class = "add-item-to-container"
  end

  def add_item
    @container = Container.can_receive_items.find(params[:id])
    inventory_item = InventoryItem.find_by(barcode: params[:barcode])

    @breadcrumbs = [ [ "Picking", choose_for_picking_containers_path ], @container.display_text ]

    if inventory_item.nil?
      @success = false
      @error = "Item #{params[:barcode]} not found."
    elsif inventory_item.container == @container
      @success = false
      @error = "Item #{params[:barcode]} already in container."
    elsif !inventory_item.can_be_added_to_container?
      @success = false
      @error = "Item cannot be added to container - #{inventory_item.can_be_added_to_container_failure_reason}"
    else
      @success = flash[:success] = true
      flash[:success_message] = "Item #{params[:barcode]} added to container."
      inventory_item.add_to_container!(@container, picked_by: current_user)
    end

    respond_to do |format|
      if @success
        format.html { redirect_to pick_container_path(@container, inventory_item_sort: params[:inventory_item_sort]) }
        format.json { render :show, status: :ok, location: @container }
      else
        format.html { render :pick, status: :unprocessable_entity }
        format.json { render json: @container.errors, status: :unprocessable_entity }
      end
    end
  end

  def remove_item
    container = Container.can_receive_items.find(params[:id])
    inventory_item = container.inventory_items.find(params[:inventory_item_id])

    raise "Container cannot be modified." unless container.can_receive_items?

    inventory_item.remove_from_container!
    respond_to do |format|
      format.html { redirect_to container_path(container, inventory_item_sort: params[:inventory_item_sort]), notice: "Item removed." }
      format.json { render :show, status: :ok, location: container }
    end
  end

  def items
    render partial: "inventory_items", locals: { container: @container }
  end

  def summary
    @breadcrumbs = [ [ "Containers", containers_path ], [ @container.display_text, container_path(@container) ], "Count summary" ]

    # We list all categories even if there is nothing in this container for them.
    @supply_categories, @equipment_categories = ItemCategory.order(:name).partition(&:supply?)
    per_category_scope = @container.inventory_items.joins(:item_subcategory)
    @item_counts = per_category_scope.group(:item_category_id).count
    grouped_categories = per_category_scope.group_by(&:item_category_id)
    @item_values = grouped_categories.map { |item_category_id, items| [ item_category_id, items.sum(&:value) ] }.to_h
    @item_weights = grouped_categories.map { |item_category_id, items| [ item_category_id, items.sum(&:weight) ] }.to_h
  end

  def manifest
    @printable_title = "Manifest"
    @printable_page_title = "Container ##{@container.application_number} Manifest"
  end

  def certificate_of_donation
    @printable_title = "Certificate of Donation"
    @printable_page_title = "Container ##{@container.application_number} Certificate of Donation"
  end

  def packing_list
    @printable_title = "Packing List"
    @printable_page_title = "Container ##{@container.application_number} Packing List"
  end

  private

  def container_params
    params.require(:container).permit(:application_number, :consignee_name, :consignee_address, :consignee_city, :consignee_region, :consignee_country, :consignee_postal_code, :consignee_contact_name, :consignee_contact_phone, :consignee_contact_email)
  end

  def set_container
    @container = Container.find_by(id: params[:id])
  end
end

app/helpers/container_helper.rb
module ContainerHelper
  def container_items_for_printable(container)
    container.inventory_items.includes(item_subcategory: :item_category).order(classification: :desc, item_category: { name: :asc }, item_subcategory: { name: :asc }, barcode: :asc)
  end

  def summarized_container_items_for_printable(container)
    items = container_items_for_printable(container)
    items.group_by { |item| item.supply? ? :supply : item.item_category.name }.map do |category, items_in_category|
      [ category, items_in_category.count, items_in_category.sum(&:value) ]
    end
  end
end

app/views/containers/_inventory_items.html.erb
<%# locals: (container:) -%>

<%= turbo_frame_tag 'inventory_items_list', target: '_top' do %>
  <% inventory_items = apply_inventory_item_sorts_and_filters(container.inventory_items, context: :picking) %>

  <% if inventory_items.any? %>
    <table class="data-table">
      <thead>
        <tr>
          <th class="numeric">Barcode <%= list_sort_link(param_name: :inventory_item_sort, param_value: :barcode) %></th>
          <th>Category <%= list_sort_link(param_name: :inventory_item_sort, param_value: :category) %></th>
          <th>Picked by <%= list_sort_link(param_name: :inventory_item_sort, param_value: :picked_by) %></th>
          <th>Picked at <%= list_sort_link(param_name: :inventory_item_sort, param_value: nil) %></th>
        </tr>
      </thead>
      <tbody>
        <% inventory_items.each do |inventory_item| %>
          <tr>
            <td class="numeric"><%= inventory_item.barcode %> </td>
            <td><%= link_to(inventory_item.item_subcategory.display_name, inventory_item.item_subcategory) %></td>
            <td><%= render_user(inventory_item.picked_by) %></td>
            <td><%= render_datetime(inventory_item.picked_at) %></td>
            <td class="action-column">
              <%= link_to '🔎', inventory_item, title: 'View' %>
            </td>
            <td class="action-column">
              <% if container.can_receive_items? %>
                <%= link_to '✖', remove_item_container_path(container, inventory_item_id: inventory_item.id, inventory_item_sort: params[:inventory_item_sort]), title: 'Remove from container', data: { turbo_method: :delete, turbo_confirm: "Return #{inventory_item.item_subcategory.display_name} to inventory?", turbo_frame: '_self' } %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <p>No inventory items packed.</p>
  <% end %>
<% end %>

app/views/containers/_printable_charity_number_footer.html.erb
<p id="container-printable-charity-number-footer">
  Canada Charity Registration Number <%= Setting.fetch(:ihc_charity_number) %>
</p>

app/views/containers/_printable_consignee.html.erb
<%# locals: (container:) %>

<p id="container-printable-consignee">
  <div class="container-printable-name-label">Consignee:</div>
  <%= safe_join([:consignee_name, :consignee_address, :consignee_city_region_country, :consignee_postal_code].map {|field| container.public_send(field)}.select(&:present?), '<br>'.html_safe) %><br>
  <% contact_fields = [:consignee_contact_name, :consignee_contact_phone, :consignee_contact_email].map {|field| container.public_send(field)}.select(&:present?) %>
  <% if contact_fields.any? %>
    Contact:<br>
    <%= safe_join(contact_fields, '<br>'.html_safe) %>
  <% end %>
</p>

app/views/containers/_printable_donor.html.erb
<div id="container-printable-donor">
  <div class="container-printable-name-label">Donor:</div>
	<%= simple_format(Setting.fetch(:ihc_address)) %>
</div>

app/views/containers/_printable_preamble.html.erb
<%# locals: (container:) %>

<div id="container-printable-preamble">
  <p>To Whom It May Concern:</p>

  <p>The items described below are unsolicited free donations from the people of Canada to the people of <%= container.consignee_city_region_country %>.</p>

  <p>The items are for humanitarian purposes only and not for sale, barter or rent.</p>
</div>

app/views/containers/certificate_of_delivery.html.erb
<table class="container-printable-table">
  <thead>
    <tr>
      <th class="numeric">Row No.</th>
      <th>Description</th>
      <th class="numeric">Quantity</th>
      <th class="numeric">Unit</th>
      <th class="numeric">Ext.</th>
    </tr>
  </thead>
  <tbody>
    <% row_number = 0 %>
    <% items = summarized_container_items_for_printable(@container) %>
    <% items.each do |subcategory, count, total_value| %>
      <tr>
        <td class="numeric"><%= row_number += 1 %></td>
        <td><%= subcategory.display_name %></td>
        <td class="numeric"><%= count %></td>
        <td class="numeric"><%= number_to_currency(subcategory.value || subcategory.item_category.value || 0) %></td>
        <td class="numeric"><%= number_to_currency(total_value) %></td>
      </tr>
    <% end %>
    <tr class="container-printable-table-total">
      <td class="numeric"><%= row_number += 1 %></td>
      <td>Total</td>
      <td class="numeric"><%= items.sum(&:second) %></td>
      <td></td>
      <td class="numeric"><%= number_to_currency(items.sum(&:third)) %></td>
    </tr>
  </tbody>
</table>

app/views/containers/certificate_of_donation.html.erb
<%= render partial: 'printable_preamble', locals: { container: @container } %>

<table class="container-printable-table">
  <thead>
    <tr>
      <th class="numeric">Row No.</th>
      <th>Description</th>
      <th></th>
      <th class="numeric">Quantity</th>
      <th class="numeric">Ext. Value</th>
    </tr>
  </thead>
  <tbody>
    <% row_number = 0 %>
    <% items = summarized_container_items_for_printable(@container) %>
    <% items.each do |category_name, count, total_value| %>
      <tr>
        <td class="numeric"><%= row_number += 1 %></td>
        <td><%= category_name == :supply ? 'Boxes of medical supplies' : category_name %></td>
        <td><%= 'Used' unless category_name == :supply %></td>
        <td class="numeric"><%= count %></td>
        <td class="numeric"><%= number_to_currency(total_value) %></td>
      </tr>
    <% end %>
    <tr class="container-printable-table-total">
      <td class="numeric"><%= row_number += 1 %></td>
      <td>Total</td>
      <td></td>
      <td class="numeric"><%= items.sum(&:second) %></td>
      <td class="numeric"><%= number_to_currency(items.sum(&:third)) %></td>
    </tr>
  </tbody>
</table>

<%= render partial: 'printable_consignee', locals: { container: @container } %>

<%= render partial: 'printable_donor' %>

<%= render partial: 'printable_charity_number_footer' %>

app/views/containers/choose_for_picking.html.erb
<% if @containers.any? %>
  <p>Choose a container to add inventory to.</p>

  <% @containers.each do |container| %>
    <%= link_to container.display_text, pick_container_path(container) %><br>
  <% end %>
<% else %>
  <p>No containers available.</p>
<% end %>

app/views/containers/index.html.erb
<div class="page-actions">
  <p>
    <%= link_to 'New container', new_container_path, class: "btn" %>
  </p>
</div>

<table class="data-table">
  <thead>
    <tr>
      <th>Application number</th>
      <th>Consignee Name</th>
      <th>Consignee Country</th>
      <th>Shipped at</th>
    </tr>
  </thead>
  <tbody>
    <% @containers.each do |container| %>
      <tr>
        <td><%= link_to(container.application_number, container) %></td>
        <td><%= container.consignee_name %></td>
        <td><%= container.consignee_country %></td>
        <td><%= render_datetime(container.shipped_at) %></td>
        <td class="action-column">
          <%= link_to('🔎', container, title: 'View') %>
        </td>
        <td class="action-column">
          <%= link_to('✎', edit_container_path(container), title: 'Edit') if container.editable? %>
          </td>
        <td class="action-column">
          <%= link_to("🗑", container, title: 'Delete', data: { turbo_method: :delete, turbo_confirm: "Deleting a container cannot be undone. Are you sure you want to delete?" }) if container.destroyable? %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= render_pagy %>
<p>
  <%= link_to 'Download CSV', containers_path(format: :csv, params: request.query_parameters), class: "btn" %>
</p>

app/views/containers/manifest.html.erb
<%= render partial: 'printable_consignee', locals: { container: @container } %>

<%= render partial: 'printable_preamble', locals: { container: @container } %>

<table class="container-printable-table">
  <thead>
    <tr>
      <th class="numeric">Row No.</th>
      <th class="numeric">Item No.</th>
      <th>Category</th>
      <th>Item</th>
      <th class="numeric">Value CDN</th>
      <th class="numeric">Approx Weight kg</th>
    </tr>
  </thead>
  <tbody>
    <% all_items = container_items_for_printable(@container) %>
    <% categorized_items = [['Equipment', all_items.where(item_category: { classification: ItemCategory.classifications[:equipment] })], ['Supplies', all_items.where(item_category: { classification: ItemCategory.classifications[:supply] })]] %>
    <% row_number = 0 %>
    <% categorized_items.each do |heading, items| %>
      <tr class="container-printable-table-heading">
        <td colspan="7"><%= heading %></td>
      </tr>
      <% items.each do |item| %>
        <tr>
          <td class="numeric"><%= row_number += 1 %></td>
          <td class="numeric"><%= item.barcode %></td>
          <td><%= item.item_category.name %></td>
          <td><%= item.item_subcategory.name %></td>
          <td class="numeric"><%= number_to_currency(item.value) %></td>
          <td class="numeric"><%= item.weight %></td>
        </tr>
      <% end %>
    <% end %>
    <tr class="container-printable-table-total">
      <td colspan="4">
        Total
      </td>
      <td class="numeric"><%= number_to_currency(all_items.sum(&:value)) %></td>
      <td class="numeric"><%= all_items.sum(&:weight) %></td>
    </tr>
  </tbody>
</table>

app/views/containers/new.html.erb
<%= form_with(model: @container, local: true) do |form| %>
  <% if @container.errors.any? %>
    <div class="error-messages">
      <h2><%= pluralize(@container.errors.count, "error") %> prohibited this container from being saved:</h2>
      <ul>
        <% @container.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :application_number %>
    <%= form.text_field :application_number, class: "form-control", required: true, inputmode: :numeric %>
  </div>

  <div class="form-group">
    <%= form.label :consignee_name %>
    <%= form.text_field :consignee_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :consignee_address %>
    <%= form.text_field :consignee_address, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :consignee_city %>
    <%= form.text_field :consignee_city, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :consignee_region %>
    <%= form.text_field :consignee_region, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :consignee_country %>
    <%= form.text_field :consignee_country, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :consignee_postal_code %>
    <%= form.text_field :consignee_postal_code, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :consignee_contact_name %>
    <%= form.text_field :consignee_contact_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :consignee_contact_phone %>
    <%= form.text_field :consignee_contact_phone, class: "form-control", inputmode: :tel %>
  </div>

  <div class="form-group">
    <%= form.label :consignee_contact_email %>
    <%= form.email_field :consignee_contact_email, class: "form-control", inputmode: :tel %>
  </div>

  <% if @container.new_record? %>
    <div class="form-actions">
      <%= form.submit "Create Container" %>
      <%= link_to 'Cancel', containers_path %>
    </div>
  <% else %>
    <div class="form-actions">
      <%= form.submit "Update Container" %>
      <%= link_to 'Cancel', container_path(@container) %>
    </div>
  <% end %>
<% end %>

app/views/containers/packing_list.html.erb
<%= render partial: 'printable_preamble', locals: { container: @container } %>

<table class="container-printable-table">
  <thead>
    <tr>
      <th class="numeric">Row No.</th>
      <th>Description</th>
      <th class="numeric">Quantity</th>
    </tr>
  </thead>
  <tbody>
    <% row_number = 0 %>
    <% items = summarized_container_items_for_printable(@container) %>
    <% items.each do |category_name, count, _total_value| %>
      <tr>
        <td class="numeric"><%= row_number += 1 %></td>
        <td><%= category_name == :supply ? 'Boxes of medical supplies' : category_name %></td>
        <td class="numeric"><%= count %></td>
      </tr>
    <% end %>
    <tr class="container-printable-table-total">
      <td class="numeric"><%= row_number += 1 %></td>
      <td>Total</td>
      <td class="numeric"><%= items.sum(&:second) %></td>
    </tr>
  </tbody>
</table>

<%= render partial: 'printable_consignee', locals: { container: @container } %>

<%= render partial: 'printable_donor' %>

<%= render partial: 'printable_charity_number_footer' %>

app/views/containers/show.html.erb
<div class="page-actions">
  <p>
    <%= link_to 'Picking', pick_container_path(@container), class: "btn" if @container.can_receive_items? %>
    <%= link_to 'Edit', edit_container_path(@container), class: "btn" if @container.editable? %>
    <%= link_to("Mark as not shipped", mark_as_not_shipped_container_path(@container), class: "btn", data: { turbo_method: :patch, turbo_confirm: "Marking a container as not shipped allows additions or removals to its contents. Are you sure?" }) if @container.shipped? %>
    <%= link_to("Mark as shipped", mark_as_shipped_container_path(@container), class: "btn", data: { turbo_method: :patch, turbo_confirm: "Marking a container as shipped prevents any further additions or removals. Are you sure?" }) if @container.can_be_marked_as_shipped? %>
    <%= link_to(@container.shipped? ? 'View manifest' : 'View draft manifest', manifest_container_path(@container), class: "btn") %>
    <%= link_to(@container.shipped? ? 'View CD' : 'View draft CD', certificate_of_donation_container_path(@container), class: "btn") %>
    <%= link_to(@container.shipped? ? 'View packing list' : 'View draft packing list', packing_list_container_path(@container), class: "btn") %>
    <%= link_to("Delete", @container, class: "btn", data: { turbo_method: :delete, turbo_confirm: "Deleting a container cannot be undone. Are you sure you want to delete?" }) if @container.destroyable? %>
  </p>
</div>

<table class="data-table">
  <tbody>
    <tr>
      <th>Application number</th>
      <td><%= @container.application_number %></td>
    </tr>
    <tr>
      <th>Consignee name</th>
      <td><%= @container.consignee_name %></td>
    </tr>
    <tr>
      <th>Consignee address</th>
      <td><%= @container.consignee_address %></td>
    </tr>
    <tr>
      <th>Consignee city</th>
      <td><%= @container.consignee_city %></td>
    </tr>
    <tr>
      <th>Consignee region</th>
      <td><%= @container.consignee_region %></td>
    </tr>
    <tr>
      <th>Consignee country</th>
      <td><%= @container.consignee_country %></td>
    </tr>
    <tr>
      <th>Consignee postal code</th>
      <td><%= @container.consignee_postal_code %></td>
    </tr>
    <tr>
      <th>Consignee contact name</th>
      <td><%= @container.consignee_contact_name %></td>
    </tr>
    <tr>
      <th>Consignee contact phone</th>
      <td><%= @container.consignee_contact_phone %></td>
    </tr>
    <tr>
      <th>Consignee contact email</th>
      <td><%= @container.consignee_contact_email %></td>
    </tr>
    <tr>
      <th>Shipped at</th>
      <td><%= render_datetime(@container.shipped_at) %></td>
    </tr>
  </tbody>
</table>

<h2>Items</h2>
<p><%= link_to 'Count summary', summary_container_path(@container), class: "btn" %></p>
<%= render partial: 'inventory_items', locals: { container: @container} %>

app/views/containers/summary.html.erb
<table class="report-table">
  <thead>
    <tr>
      <th></th>
      <th class="numeric">Count</th>
      <th class="numeric">Weight</th>
      <th class="numeric">Value</th>
    </tr>
  </thead>
  <tbody>
    <% data = [['Supplies', @supply_categories], ['Equipment', @equipment_categories]] %>
    <% data.each do |heading, categories| %>
      <tr class="heading-row">
        <td colspan=4>
          <%= heading %>
        </td>
      </tr>
      <% categories.each do |category| %>
        <tr>
          <th><%= category.name %></th>
          <td class="numeric"><%= @item_counts[category.id] || 0 %></td>
          <td class="numeric"><%= number_with_precision(@item_weights[category.id] || 0, precision: 1) %> kg</td>
          <td class="numeric"><%= number_to_currency(@item_values[category.id] || 0) %></td>
        </tr>
      <% end %>
      <tr class="total-row">
        <th>Total</th>
        <td class="numeric"><%= @item_counts.values_at(*categories.map(&:id)).compact.sum(0) %></td>
        <td class="numeric"><%= number_with_precision(@item_weights.values_at(*categories.map(&:id)).compact.sum(0), precision: 1) %> kg</td>
        <td class="numeric"><%= number_to_currency(@item_values.values_at(*categories.map(&:id)).compact.sum(0)) %></td>
      </tr>
    <% end %>
    <tr class="heading-row">
      <td colspan=4>
        Total
      </td>
    </tr>
    <tr class="total-row">
      <th></th>
      <% all_categories = data.map(&:last).flatten %>
      <td class="numeric"><%= @item_counts.values_at(*all_categories.map(&:id)).compact.sum(0) %></td>
      <td class="numeric"><%= number_with_precision(@item_weights.values_at(*all_categories.map(&:id)).compact.sum(0), precision: 1) %> kg</td>
      <td class="numeric"><%= number_to_currency(@item_values.values_at(*all_categories.map(&:id)).compact.sum(0)) %></td>
    </tr>
  </tbody>
</table>